package com.xtensus.hibernate.model;

import static javax.persistence.GenerationType.IDENTITY;

import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Annotation generated by hbm2java
 */
@Entity
@Table(name = "annotation")
public class Annotation extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -3934724866496868631L;
	private Integer annotationId;
	private String annotationLibelle;
	private String annotationDescription;
	private String annotationLibelleAr;
	private String annotationDescriptionAr;
	private Integer annotationOrdre;
	
	public Annotation() {
	}

	public Annotation(String annotationLibelle, String annotationDescription,
			String annotationLibelleAr, String annotationDescriptionAr,
			Integer annotationOrdre) {
		this.annotationLibelle = annotationLibelle;
		this.annotationDescription = annotationDescription;
		this.annotationLibelleAr = annotationLibelleAr;
		this.annotationDescriptionAr = annotationDescriptionAr;
		this.annotationOrdre = annotationOrdre;
//		this.transactions = transactions;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "annotationId", unique = true, nullable = false)
	public Integer getAnnotationId() {
		return this.annotationId;
	}

	public void setAnnotationId(Integer annotationId) {
		this.annotationId = annotationId;
	}

	@Column(name = "annotationLibelle", length = 254)
	public String getAnnotationLibelle() {
		return this.annotationLibelle;
	}

	public void setAnnotationLibelle(String annotationLibelle) {
		this.annotationLibelle = annotationLibelle;
	}

	@Column(name = "annotationDescription", length = 16277215)
	public String getAnnotationDescription() {
		return this.annotationDescription;
	}

	public void setAnnotationDescription(String annotationDescription) {
		this.annotationDescription = annotationDescription;
	}

	@Column(name = "annotationLibelle_AR", length = 16277215)
	public String getAnnotationLibelleAr() {
		return this.annotationLibelleAr;
	}

	public void setAnnotationLibelleAr(String annotationLibelleAr) {
		this.annotationLibelleAr = annotationLibelleAr;
	}

	@Column(name = "annotationDescription_AR", length = 16277215)
	public String getAnnotationDescriptionAr() {
		return this.annotationDescriptionAr;
	}

	public void setAnnotationDescriptionAr(String annotationDescriptionAr) {
		this.annotationDescriptionAr = annotationDescriptionAr;
	}

	@Column(name = "annotationOrdre")
	public Integer getAnnotationOrdre() {
		return this.annotationOrdre;
	}

	public void setAnnotationOrdre(Integer annotationOrdre) {
		this.annotationOrdre = annotationOrdre;
	}

//	@ManyToMany(fetch = FetchType.LAZY)
//	@JoinTable(name = "transactionannotation", joinColumns = { @JoinColumn(name = "idAnnotation", nullable = false, updatable = false) }, inverseJoinColumns = { @JoinColumn(name = "idTransaction", nullable = false, updatable = false) })
//	public Set<Transaction> getTransactions() {
//		return this.transactions;
//	}
//
//	public void setTransactions(Set<Transaction> transactions) {
//		this.transactions = transactions;
//	}

}
