package com.xtensus.hibernate.model;

import static javax.persistence.GenerationType.IDENTITY;


import javax.persistence.Column;
import javax.persistence.Entity;
import javax.persistence.GeneratedValue;
import javax.persistence.Id;
import javax.persistence.Table;

/**
 * Urgence generated by hbm2java
 */
@Entity
@Table(name = "urgence")
public class Urgence extends Entite implements java.io.Serializable {

	/**
	 * 
	 */
	private static final long serialVersionUID = -4045795257450126474L;
	private Integer urgenceId;
	private Integer urgenceOrdre;
	private String urgenceLibelle;
	private String urgenceDescription;
	private String urgenceLibelleAr;
	private String urgenceDescriptionAr;
//	private Set<Dossier> dossiers = new HashSet<Dossier>(0);
//	private Set<Courrier> courriers = new HashSet<Courrier>(0);

	public Urgence() {
	}

	public Urgence(Integer urgenceOrdre, String urgenceLibelle,
			String urgenceDescription, String urgenceLibelleAr,
			String urgenceDescriptionAr) {
		this.urgenceOrdre = urgenceOrdre;
		this.urgenceLibelle = urgenceLibelle;
		this.urgenceDescription = urgenceDescription;
		this.urgenceLibelleAr = urgenceLibelleAr;
		this.urgenceDescriptionAr = urgenceDescriptionAr;
//		this.dossiers = dossiers;
//		this.courriers = courriers;
	}

	@Id
	@GeneratedValue(strategy = IDENTITY)
	@Column(name = "urgenceId", unique = true, nullable = false)
	public Integer getUrgenceId() {
		return this.urgenceId;
	}

	public void setUrgenceId(Integer urgenceId) {
		this.urgenceId = urgenceId;
	}

	@Column(name = "urgenceOrdre")
	public Integer getUrgenceOrdre() {
		return this.urgenceOrdre;
	}

	public void setUrgenceOrdre(Integer urgenceOrdre) {
		this.urgenceOrdre = urgenceOrdre;
	}

	@Column(name = "urgenceLibelle", length = 254)
	public String getUrgenceLibelle() {
		return this.urgenceLibelle;
	}

	public void setUrgenceLibelle(String urgenceLibelle) {
		this.urgenceLibelle = urgenceLibelle;
	}

	@Column(name = "urgenceDescription", length = 16277215)
	public String getUrgenceDescription() {
		return this.urgenceDescription;
	}

	public void setUrgenceDescription(String urgenceDescription) {
		this.urgenceDescription = urgenceDescription;
	}

	@Column(name = "urgenceLibelle_AR", length = 254)
	public String getUrgenceLibelleAr() {
		return this.urgenceLibelleAr;
	}

	public void setUrgenceLibelleAr(String urgenceLibelleAr) {
		this.urgenceLibelleAr = urgenceLibelleAr;
	}

	@Column(name = "urgenceDescription_AR", length = 16277215)
	public String getUrgenceDescriptionAr() {
		return this.urgenceDescriptionAr;
	}

	public void setUrgenceDescriptionAr(String urgenceDescriptionAr) {
		this.urgenceDescriptionAr = urgenceDescriptionAr;
	}

//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "urgence")
//	public Set<Dossier> getDossiers() {
//		return this.dossiers;
//	}
//
//	public void setDossiers(Set<Dossier> dossiers) {
//		this.dossiers = dossiers;
//	}
//
//	@OneToMany(fetch = FetchType.LAZY, mappedBy = "urgence")
//	public Set<Courrier> getCourriers() {
//		return this.courriers;
//	}
//
//	public void setCourriers(Set<Courrier> courriers) {
//		this.courriers = courriers;
//	}

	@Override
	public String toString() {
		return "Urgence [urgenceId=" + urgenceId + ", urgenceOrdre="
				+ urgenceOrdre + ", urgenceLibelle=" + urgenceLibelle
				+ ", urgenceDescription=" + urgenceDescription + "]";
	}

}
